### ISSUE TITLE
typeerror undefined is not a function (evaluating 'object.assign')

### ISSUE THREAD

**Issue by JZLeung** [justinkames/vuejs-logger#11]
broswer: safari
os: ios 8.3
i can use `Object.assign` normally outside, but logger.install
```js
console.log(Object.assign({a: 1}, {b: 2}))
console.log(VueLogger.install)
try {
    Vue.use(VueLogger, options)
} catch (error) {
    console.error(error)
}
```
![](https://ws3.sinaimg.cn/large/006tNc79gy1fqx0k2m719j30ku112goc.jpg)

**Comment by justinkames** [comment]
@JZLeung 

Thanks, I'm gonna look into this!
