### ISSUE TITLE
Fix display of method name when using async

### ISSUE THREAD

**Issue by ejwaibel** [justinkames/vuejs-logger#14]
If the `$log` is called within a method that is defined as `async`, the output will display ` _callee$` instead of the actual method name.

Example:
```
async myFn() {
    this.$log.debug('testing');
}

myFn();
```

Output:
`debug |  _callee$ | testing`

Expected Output:
`debug | myFn | testing`

**Comment by justinkames** [comment]
Hi @ejwaibel,

Thanks for reporting this. Unfortunately this cannot be fixed ( to my knowledge ).  Async await code : 

```
function resolveAfter2Seconds() {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve('resolved');
    }, 2000);
  });
}

async function asyncCall() {
  console.log('calling');
  var result = await resolveAfter2Seconds();
  console.log(result);
  // expected output: "resolved"
}
```

Transpiles to ( ES5 )  @ https://babeljs.io/repl/  : 

```
var asyncCall = function () {
  var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee() {
    var result;
    return regeneratorRuntime.wrap(function _callee$(_context) {
      while (1) {
        switch (_context.prev = _context.next) {
          case 0:
            console.log('calling');
            _context.next = 3;
            return resolveAfter2Seconds();

          case 3:
            result = _context.sent;

            console.log(result);
            // expected output: "resolved"

          case 5:
          case 'end':
            return _context.stop();
        }
      }
    }, _callee, this);
  }));

  return function asyncCall() {
    return _ref.apply(this, arguments);
  };
}();
```

This library relies on the new Error().stack property to determine the parent function name.  Unfortunately the transpiling causes the function to be wrapped in a function called _callee$, which is logged as the parent function.

I do not see a solution for this problem at this point in time. Feel free to propose something / or create a pull request.
