### ISSUE TITLE
Add missing methods from browser Console object

### ISSUE THREAD

**Issue by ejwaibel** [justinkames/vuejs-logger#15]
Would like to see additional methods from https://developer.mozilla.org/en-US/docs/Web/API/Console to be implemented:

- `assert()` - https://developer.mozilla.org/en-US/docs/Web/API/Console/assert
- `time()` - https://developer.mozilla.org/en-US/docs/Web/API/Console/time
- `timeEnd()` - https://developer.mozilla.org/en-US/docs/Web/API/Console/timeEnd
- `trace()` - https://developer.mozilla.org/en-US/docs/Web/API/Console/trace

**Comment by justinkames** [comment]
This is not a priority now. It could become one, how would you like to see them implemented? In combination with logging functionality.
