### ISSUE TITLE
Problem resolving es6-object-assign

### ISSUE THREAD

**Issue by cory-buckley** [justinkames/vuejs-logger#19]
I'm getting the following error in one of my pipelines. I've switch to using vuejs-logger@1.4.0 since that appears to be the last version that doesn't cause this error.

Module not found: Error: Can't resolve 'es6-object-assign' in '/opt/atlassian/pipelines/agent/build/node_modules/vuejs-logger/dist'

**Comment by justinkames** [comment]
@cory-buckley thanks for reporting, working on it now.
