### ISSUE TITLE
Logging object

### ISSUE THREAD

**Issue by kovacevjosip** [justinkames/vuejs-logger#20]
Hi,
is it possible to log object to console with new version of vuejs-logger (v1.5.2).
It always logs like [object Object].

This was working fine with version 1.4.0

**Comment by justinkames** [comment]
Hi @kovacevjosip,

Thanks. Yeah this is a bug, should work. Will fix it.

**Comment by justinkames** [comment]
Published @ vuejs-logger@1.5.3. Thanks for reporting!
