### ISSUE TITLE
Version numbers confusing dependency upgrade tools

### ISSUE THREAD

**Issue by scottpage** [justinkames/vuejs-logger#30]
Node:  10.15.2
Npm:  6.9.0
Vue:  3.4.1

When I run `Vue UI` and browse the Dependencies tab of any project Vue project using vuejs-logger, I see an upgrade notification due to version `1.10.2` seeming to be a more recent version than the latest (i.e. `1.5.3`).

Running an update on all dependencies works as expected, and vuejs-logger is not downgraded.  So I  believe this may just be an issue with `Vue UI` seeing the version number as a string, instead of numbers, and assuming an upgrade is needed.  `NPM` must not use the same character encoding when actually performing the updates, so it performs as expected.

If this can be safely ignored, I have no problem with that.  Should I file an issue in the vue-cli repo instead?

**Comment by justinkames** [comment]
Hi @scottpage. Thanks for your message. I think you should file an issue with them instead!
