### ISSUE TITLE
Showing all logLevels even when config is set to one type.

### ISSUE THREAD

**Issue by runrog** [justinkames/vuejs-logger#32]
I'm not sure if this is a bug but I currently have a config like so

```javascript
Vue.use(VueLogger, {
  logLevels: 'error',
  stringifyArguments: false,
  showLogLevel: true,
  showMethodName: false,
  showConsoleColors: true,
});
```
and in my app I'm calling the logger like so

```javascript
this.$log.debug('test debug');
this.$log.info('test info');
this.$log.error('test error');
```

and all of these log to the console. Shouldn't it only show the error?

Using latest version @1.5.3

**Comment by justinkames** [comment]
@runrog The log level setting in this plugin is restrictive, meaning it will show all log levels up to that log level 

'error' means it shows debug,info,warn messages
'info' means it only shows debug,info messages

```
logLevels :  ['debug', 'info', 'warn', 'error', 'fatal']
```
