### ISSUE TITLE
TypeError raised on IE11

### ISSUE THREAD

**Issue by hirakiuc** [justinkames/vuejs-logger#5]
Thanks for the good npm package! 👍 

But, this logger throws TypeError when I use this on IE11.

```
TypeError: Unable to get property 'split' of undefined or null reference
```

I investigate my issue and found this document finally.

https://docs.microsoft.com/en-us/scripting/javascript/reference/stack-property-error-javascript#remarks

> The stack property is set to undefined when the error is constructed, and gets the trace information when the error is raised. 

I think [this code](https://github.com/justinkames/vuejs-logger/blob/master/src/logger.js#L75) is the 
 cause of my problem.

Thanks.

**Comment by justinkames** [comment]
Hi @hirakiuc,

Thanks for reporting this one. Will fix it asap.

Regards,

Justin

**Comment by justinkames** [comment]
fdc6d23fd0107484129dca1bb25daa8ebd092265

**Comment by hirakiuc** [comment]
Thanks, @justinkames .

But, [this code](https://github.com/justinkames/vuejs-logger/commit/fdc6d23fd0107484129dca1bb25daa8ebd092265#diff-567859a4cc8b910de0454da79959bde6R79) uses `String.prototype.includes` which is not supported by IE.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes#Browser_compatibility

So, I use the vuejs-logger 1.3.4 with the `String.prototype.includes` polyfill, it works! 👍
