### ISSUE TITLE
Possible to use in development only?

### ISSUE THREAD

**Issue by loweoj** [justinkames/vuejs-logger#6]
Hi,  thanks for a really useful plugin.

I'm curious, is it possible to use this only for development, and possibly to strip out/disable logging in a production build?

**Comment by justinkames** [comment]
Hi @loweoj ,

Yes this is possible. You can specifiy the log level in when the webpack build step is executed. In the example below you could set DEBUG_LEVEL=fatal ( the most restrictive logging level ), and it will ignore all messages that are not fatal.

```
const options = {
    logLevel : process.env.DEBUG_LEVEL, 
    .....
}
```

$ DEBUG_LEVEL=fatal webpack

Does this answer your question?

Regards,

Justin
