### ISSUE TITLE
Does this support logging to an HTTP endpoint on my server?

### ISSUE THREAD

**Issue by light24bulbs** [justinkames/vuejs-logger#7]
Is this just a local logging client?

**Comment by justinkames** [comment]
@light24bulbs 

Hey, thanks for the suggestion. I will look into making this configurable and come back to you.

Regards,

Justin

**Comment by justinkames** [comment]
@light24bulbs 

I've looked into it and for now this is not a priority, so I'm closing the issue. You can always submit a pull request with this functionality.
