### ISSUE TITLE
Type error raised in IE9

### ISSUE THREAD

**Issue by timberkeley** [justinkames/vuejs-logger#8]
"TypeError: Unable to get value of the property 'split': object is null or undefined"

This is again a problem with stack traces in IE, error.stack is undefined. I would think that the simplest option would to just return no method name for such an old and broken browser.

``` javascript
  try { throw new Error('') } catch (e) { error = e }
  if (error.stack === undefined) {
    return ""
  }
```

**Comment by justinkames** [comment]
@timberkeley 

Thanks for the suggestion, I will update the the library so it is compatible with IE9.
